language: node_js
sudo: false
node_js:
- '10'
- '12'
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  - provider: npm
    email: mick@heise.de
    api_key:
      secure: "FaqCdlJroVVkN498GncaLr0X3rt51Ep8LzObEx4I1/bOfbpgmr1aliDNxEB2vWQ2i1kL5r5w7mtzNx8a2VqdlVMlQshleh4un0jlA3Jl4OD7OFeckw7w1CUqlH5XaGPOUYbt44axKl2/GmsCt5DyAzDB1xxPam7Ac8icPAU40i5Px3ZqPUir2ZTJHjxikF8dI5thQCCYVJYyTyr+jJx3V9SiemWWGGn51hECltk7VWCQ7v64ZCuw7+oa5EH9zY150rDR3U9HUldl4jitQxOE3F1mjz600qC10Iaex3OYpZCHpDdUgmhXUq5pvC9pnuVdSCpo6PMR6rbsk80581T8zLd/MdAmY5jYH2YlM5bM2gyz87Y74vHQNjEXV7X7mfv0WAZEc9VKXSBhpj7WtAAJBgXpI7eZ4ohKYgVeds1PdxRZIlt/k7p03PL4gSLOYH5Io8y86wowUEiK+s6cQni1GR/6kOeIc8nRrjDR9gu07uKVYGyuOvPYFZT3PZXhSNv5U8+J4EDgPh8/m0m4hv4l4paBIhTQFsuGpDYGY5Z4PEm0qX2BmN365VTlpPwNDTCLuqzUFaBixJZg3KqMWcaCF7iQfQWdIxvjbBCC+sXNEiY5HstVXlcv/CWvff/fXYIXuwhS5f4FZwH9YUR0uvATuFjJ2jVxbjtCXP9sbdmBvZI="
    on:
      tags: true
      repo: heiseonline/embetty-server
      node_js: '8'
  - provider: releases
    api_key:
      secure: Vo1gHWeP+02o3kTRqC5LjdowXkXmd1wgnuyzBWnYYqt3+Q2k67QxgqxzWXK1lGPKSy/1fqdnRcczd7QG81vAmCbSA6Apykr/9tYi+bSUfRpPSdlnL1Eq/GaV8zOlt8U22xxtUTiCcw6N5W89Mzi42EoYuDF4/16Y8d289lIwyZuBS61BRPpaIXCp0cLIcz9XVnxeCdAI/gtTCKMSc29CaUDYRFR8YQUvbQOsdSGDVzgDNhR+vuD5q2WJgFW/rqIIcq4oSlDVK0FmRmS21aR+s5EWxlNIs2PN/0UL3ubpnlJbMpNK0FGdnBQSORKE0y4DrQ6sLAT+dw/3UwNcpx7w486+fgkuzmsqtqnzpe8n9tMpduQYjl+6oF14xgevGDorKEr7Vy/GRThM+adfZmzpJ9z2iT6cpIC1ZvQ9hXC+dO0QRv44T30W0xB+40pI2e+9biDBOg5YEm/BD0n3KLkBFhFPSlOJSah3d0Pp4BxW+fsCHrkUehbcZ5uMuCPfgx4Rjx37uaVp81fvRL1SGLFtTz8oOPrqt1exl84MCTqdt0mSdoi9+HUUkLvFIfGM7et3x4rsb81HLGfY2cecNCqR9Vw/Hxe3SBBEoNWnpn6EmNgL/zF7zcJYuV58fEp/o7ytQnNAvAFBcepH24Xh7D6Ik2oIvN48ityHY5x+vBFyLao=
    on:
      repo: heiseonline/embetty-server
      tags: true
